version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    commit_message:
      prefix: NONJIRA
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
      - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    labels:
      - "Dependabot"
    pull-request-branch-name:
      separator: _
