name: Dependencies Checker

on: 
  workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant permission
      run: chmod +x gradlew
    - name: Lint
      id: lint
      continue-on-error: true
      run: ./gradlew dependencyUpdates -Drevision=release -DoutputFormatter=html -DreportfileName=jhoangamarraReport
    - uses: MeilCli/gradle-update-check-action@v3
      id: outdated
    - uses: 8398a7/action-slack@v2
      if: steps.outdated.outputs.has_maven_update != 'false'
      with:
        status: ${{ job.status }}
        text: ${{ steps.outdated.outputs.maven_update_json }}
        author_name: Jhoan Gamarra
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
