name: Dependencies Checker

on: 
  workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant permission
      run: chmod +x gradlew
    - name: Dependencies Reporter
      run: ./gradlew dependencyUpdates
    - uses: fabasoad/yaml-json-xml-converter-action@main
      id: formatJson
      with:
        path: '/home/runner/work/CL-Challenge/CL-Challenge/app/build/dependencyUpdates/proreport2.json'
        from: 'json'
        to: 'json'
    - name: notification
      uses: edge/simple-slack-notify@master
      env:
        SLACK_WEBHOOK_URL: ${{ https://hooks.slack.com/services/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 }}
      with:
        channel: '#bot'
        text: ${{ steps.formatJson.outputs.data }}
        color: 'good'
        success_text: 'Dependencies checker was finished successfully'
        fields: |
          [{ "title": "Checker", "value": "Oudated Libraries", "short": true }]
