name: Dependencies Checker

on: 
  workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant permission
      run: chmod +x gradlew
    - name: Dependencies Reporter
      run: ./gradlew dependencyUpdates -Drevision=release -DoutputFormatter=json
    - name: ls folder
      run: ls 
    - name: ls folder
      run: ls /home/runner/work/CL-Challenge/CL-Challenge
    - uses: fabasoad/yaml-json-xml-converter-action@main
      id: json2yml
      with:
        path: 'build/dependencyUpdates/report.json'
        from: 'json'
        to: 'yaml'
    - uses: fabasoad/yaml-json-xml-converter-action@main
      id: formatJson
      with:
        path: '/home/runner/work/CL-Challenge/CL-Challenge/build/dependencyUpdates/report.json'
        from: 'json'
        to: 'json'
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        text: ${{ steps.formatJson.outputs.data }}
        author_name: Jhoan Gamarra
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: bot
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: ${{ steps.formatJson.outputs.data }}
        SLACK_TITLE: 'Dependencies Checker'
        SLACK_USERNAME: bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
