name: Dependencies Checker

on: 
  workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant permission
      run: chmod +x gradlew
    - name: Dependencies Reporter
      run: ./gradlew dependencyUpdates
    - uses: fabasoad/yaml-json-xml-converter-action@main
      id: json2yml
      with:
        path: '/home/runner/work/CL-Challenge/CL-Challenge/app/build/dependencyUpdates/proreport2.json'
        from: 'json'
        to: 'yaml'
    - uses: fabasoad/yaml-json-xml-converter-action@main
      id: formatJson
      with:
        path: '/home/runner/work/CL-Challenge/CL-Challenge/app/build/dependencyUpdates/proreport2.json'
        from: 'json'
        to: 'json'
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        text: ${{ steps.formatJson.outputs.data }}
        author_name: Bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        text: ${{ steps.json2yml.outputs.data }}
        author_name: Bot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
