name: Dependencies Checker

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '* * * * *'
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant permission
      run: chmod +x gradlew
    - name: Dependencies Reporter
      run: ./gradlew dependencyUpdates
    - uses: fabasoad/yaml-json-xml-converter-action@main
      id: formatJson
      with:
        path: '/home/runner/work/CL-Challenge/CL-Challenge/app/build/dependencyUpdates/proreport2.json'
        from: 'json'
        to: 'json'
    - name: notification
      uses: edge/simple-slack-notify@master
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
      with:
        status: ${{ job.status }}
        text: ${{ steps.formatJson.outputs.data }}
        color: 'good'
        success_text: 'Dependencies checker was finished successfully'
        fields: |
          [{ "title": "Wallet Outdated Libraries", "value": "Libraries that need your review", "short": true }]
